(function() {var implementors = {};
implementors["slog"] = [];
implementors["slog_async"] = [{text:"impl <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_async/struct.AsyncCore.html\" title=\"struct slog_async::AsyncCore\">AsyncCore</a>",synthetic:false,types:["slog_async::AsyncCore"]},{text:"impl <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_async/struct.Async.html\" title=\"struct slog_async::Async\">Async</a>",synthetic:false,types:["slog_async::Async"]},];
implementors["slog_envlogger"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a>&gt; <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_envlogger/struct.EnvLogger.html\" title=\"struct slog_envlogger::EnvLogger\">EnvLogger</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a>&lt;Ok = <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt;,&nbsp;</span>",synthetic:false,types:["slog_envlogger::EnvLogger"]},];
implementors["slog_stdlog"] = [{text:"impl <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_stdlog/struct.StdLog.html\" title=\"struct slog_stdlog::StdLog\">StdLog</a>",synthetic:false,types:["slog_stdlog::StdLog"]},];
implementors["slog_term"] = [{text:"impl&lt;D&gt; <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_term/struct.FullFormat.html\" title=\"struct slog_term::FullFormat\">FullFormat</a>&lt;D&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;D: <a class=\"trait\" href=\"slog_term/trait.Decorator.html\" title=\"trait slog_term::Decorator\">Decorator</a>,&nbsp;</span>",synthetic:false,types:["slog_term::FullFormat"]},{text:"impl&lt;D&gt; <a class=\"trait\" href=\"slog/trait.Drain.html\" title=\"trait slog::Drain\">Drain</a> for <a class=\"struct\" href=\"slog_term/struct.CompactFormat.html\" title=\"struct slog_term::CompactFormat\">CompactFormat</a>&lt;D&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;D: <a class=\"trait\" href=\"slog_term/trait.Decorator.html\" title=\"trait slog_term::Decorator\">Decorator</a>,&nbsp;</span>",synthetic:false,types:["slog_term::CompactFormat"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
