(function() {var implementors = {};
implementors["bitflags"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"struct\" href=\"bitflags/example_generated/struct.Flags.html\" title=\"struct bitflags::example_generated::Flags\">Flags</a>&gt; for <a class=\"struct\" href=\"bitflags/example_generated/struct.Flags.html\" title=\"struct bitflags::example_generated::Flags\">Flags</a>",];
implementors["either"] = ["impl&lt;L, R, A&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A&gt; for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;R: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A&gt;,&nbsp;</span>",];
implementors["rustc_data_structures"] = ["impl&lt;A:&nbsp;<a class=\"trait\" href=\"rustc_data_structures/array_vec/trait.Array.html\" title=\"trait rustc_data_structures::array_vec::Array\">Array</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A::<a class=\"type\" href=\"rustc_data_structures/array_vec/trait.Array.html#associatedtype.Element\" title=\"type rustc_data_structures::array_vec::Array::Element\">Element</a>&gt; for <a class=\"struct\" href=\"rustc_data_structures/array_vec/struct.ArrayVec.html\" title=\"struct rustc_data_structures::array_vec::ArrayVec\">ArrayVec</a>&lt;A&gt;","impl&lt;A:&nbsp;<a class=\"trait\" href=\"rustc_data_structures/array_vec/trait.Array.html\" title=\"trait rustc_data_structures::array_vec::Array\">Array</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A::<a class=\"type\" href=\"rustc_data_structures/array_vec/trait.Array.html#associatedtype.Element\" title=\"type rustc_data_structures::array_vec::Array::Element\">Element</a>&gt; for <a class=\"struct\" href=\"rustc_data_structures/small_vec/struct.SmallVec.html\" title=\"struct rustc_data_structures::small_vec::SmallVec\">SmallVec</a>&lt;A&gt;","impl&lt;I:&nbsp;<a class=\"trait\" href=\"rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a>, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;T&gt; for <a class=\"struct\" href=\"rustc_data_structures/indexed_vec/struct.IndexVec.html\" title=\"struct rustc_data_structures::indexed_vec::IndexVec\">IndexVec</a>&lt;I, T&gt;","impl&lt;D:&nbsp;<a class=\"trait\" href=\"rustc_data_structures/snapshot_vec/trait.SnapshotVecDelegate.html\" title=\"trait rustc_data_structures::snapshot_vec::SnapshotVecDelegate\">SnapshotVecDelegate</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;D::<a class=\"type\" href=\"rustc_data_structures/snapshot_vec/trait.SnapshotVecDelegate.html#associatedtype.Value\" title=\"type rustc_data_structures::snapshot_vec::SnapshotVecDelegate::Value\">Value</a>&gt; for <a class=\"struct\" href=\"rustc_data_structures/snapshot_vec/struct.SnapshotVec.html\" title=\"struct rustc_data_structures::snapshot_vec::SnapshotVec\">SnapshotVec</a>&lt;D&gt;",];
implementors["smallvec"] = ["impl&lt;A:&nbsp;<a class=\"trait\" href=\"smallvec/trait.Array.html\" title=\"trait smallvec::Array\">Array</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;A::<a class=\"type\" href=\"smallvec/trait.Array.html#associatedtype.Item\" title=\"type smallvec::Array::Item\">Item</a>&gt; for <a class=\"struct\" href=\"smallvec/struct.SmallVec.html\" title=\"struct smallvec::SmallVec\">SmallVec</a>&lt;A&gt;",];
implementors["syn"] = ["impl&lt;T, P&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;T&gt; for <a class=\"struct\" href=\"syn/punctuated/struct.Punctuated.html\" title=\"struct syn::punctuated::Punctuated\">Punctuated</a>&lt;T, P&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;P: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>,&nbsp;</span>","impl&lt;T, P&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"enum\" href=\"syn/punctuated/enum.Pair.html\" title=\"enum syn::punctuated::Pair\">Pair</a>&lt;T, P&gt;&gt; for <a class=\"struct\" href=\"syn/punctuated/struct.Punctuated.html\" title=\"struct syn::punctuated::Punctuated\">Punctuated</a>&lt;T, P&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
